version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: cnd-backend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - cnd-network-prod
    # En production, pas de volumes montés pour les sources
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: cnd-frontend-prod
    ports:
      - "80:5173"  # Mappé le port 80 externe vers 5173 interne
      - "443:443"  # Pour HTTPS
    depends_on:
      - backend
    restart: always
    networks:
      - cnd-network-prod
    # Ajouter des volumes pour les certificats SSL si nécessaire
    # volumes:
    #   - ./ssl:/etc/nginx/ssl

networks:
  cnd-network-prod:
    driver: bridge
